### ISSUE TITLE
Empty output for variable-style definitions

### ISSUE THREAD

**Issue by laurence-myers** [jeremyfa/node-ts2hx#2]
A simple example:
https://github.com/borisyankov/DefinitelyTyped/blob/master/add2home/add2home.d.ts
Defines one variable, an object with three functions. The converted output is empty:

```
package;


//# lineMapping=
```

**Comment by jeremyfa** [comment]
Hi Laurence,

This output is expected as the construct your are providing is not supported by ts2hx. Variable definitions at the root of the file are ignored because there is no equivalent in Haxe. Everything should be encapsuled in a class or interface if you want to transpile it to Haxe properly.

More than that: ts2hx is not expecting a Typescript definition file but a real Typescript file with implemented method bodies.

I hope this helps :)

**Comment by laurence-myers** [comment]
Ah I see, thanks for the info Jérémy! I was not aware of the difference between TypeScript implementation files and TypeScript declaration files. I was hoping to automatically translate some TypeScript definitions into Haxe JS externs. No worries!

Can I suggest you add something in the README, saying that definition files cannot be converted?

**Comment by jeremyfa** [comment]
Sure, I will add it once I freshen up a bit this repo :).
